name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.0

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1.2.0

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1.0.1

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1.2.0
        with:
          action: "fix"
          only-changed-files: true