name: Push Tasks

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Reformat C# Code
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    env:
      working-directory : ./WebHRModuleWizard/    
    
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - run: dotnet tool install -g dotnet-format
      - name: format
        run: dotnet-format -v d
        working-directory: ${{env.working-directory}}
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "[Bot-C#] Automated format update"
          add: "*.cs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}